### ISSUE TITLE
SSD-Resnet34 NHWC model

### ISSUE THREAD

**Issue by aaronzhongii** [mlcommons/inference_policies#126]
as in https://github.com/mlperf/inference/issues/219, someone (or maybe the model owner) provides a new link in zenodo for both NHWC and NCHW model download for SSD-Resnet34. I have tried the NHWC model at my local and verified accuracy at 22.761%, which is pretty good. I suggest to update the zenodo link of SSD model in v0.5/classification_and_detection/README.md with this new link.

**Comment by christ1ne** [comment]
@christ1ne to check the status of the both models.
WG: not an issue anymore since the model conversion script is working. 
@aaronzhongii can you share the script link? 

Thanks!

**Comment by aaronzhongii** [comment]
The link to the nchw to nhwc conversion script

**Comment by christ1ne** [comment]
closing this issue as we have a working conversion script
