### ISSUE TITLE
99% or 99.9% percent rule applied per FP32 model or min FP32 accuracy

### ISSUE THREAD

**Issue by christ1ne** [mlcommons/inference_policies#139]
Let's decide if the rule is still for 99% and/or 99.9% at per model level or min. of all FP32 models per benchmark

**Comment by tjablin** [comment]
The potential choices are min, average, max, or per model.

**Comment by TheKanter** [comment]
This was primarily motivated by SSD-ResNet where PyTorch/TF/ONNX accuracies are different. The solution is contained in C++ code in https://meet.google.com/linkredirect?authuser=0&dest=https%3A%2F%2Fgithub.com%2Fmlperf%2Finference%2Fpull%2F659

This needs to be fixed at the benchmark in v0.8.

**Comment by TheKanter** [comment]
Delay issues to v0.8

**Comment by psyhtest** [comment]
It's likely to be fixed by reimplementing SSD-ResNet.

**Comment by christ1ne** [comment]
WG: the current proposal is still using min FP32 accuracy. Let's discuss and finalize next week.

**Comment by christ1ne** [comment]
WG: there is no change to the accuracy threshold in v1.0.

**Comment by kstreee-furiosa** [comment]
Hi all, any updates here? will it be the same in v1.1?

**Comment by rnchukka** [comment]
Since we passed the Inference freeze deadline, I assume the rule will remain the same. Adding @guschmue @tjablin for comments.
