### ISSUE TITLE
Reducing the burden of Edge submitters

### ISSUE THREAD

**Issue by psyhtest** [mlcommons/inference_policies#150]
From the v0.7 round, each Edge submission must provide results for the SingleStream and Offline scenarios. It can be a huge burden for Edge submitters where the inference time can be in the order of seconds. For example, dividiti's v0.5 submission of [ResNet via TFLite on Raspberry Pi 4](https://github.com/mlperf/inference_results_v0.5/blob/master/closed/dividiti/results/rpi4-tflite-v1.15/resnet/singlestream/performance/run_1/mlperf_log_summary.txt) took 1.9 seconds per sample in the SingleStream scenario. Thus, it took ~27 hours to run through the ImageNet validation dataset of 50,000 samples in the accuracy mode.

The Offline scenario requires as many samples in the accuracy mode, and at least 24,576 samples in the performance mode. For resource-constrained implementations, no significant performance improvement is expected for the Offline scenario e.g. from batching. Therefore, the inference time per sample would be roughly the same as for the SingleStream scenario. For the above example, this would translate into ~40 more hours. In total, it would take nearly 3 days (assuming no restarts would be required, which may not be the case).

I suggest to consider the following ideas:
1. Allow to _reuse_ accuracy runs between scenarios. For example, the log from a SingleStream accuracy run could be copied into an Offline and/or MultiStream result, provided the run options are the same (SUT, benchmark, etc.)
2. Allow to _infer_ Offline results from SingleStream results. For example, a SingleStream ResNet50 result of 20 ms per sample would be counted as 50 samples per second for the Offline scenario.
3. Allow to _infer_ MultiStream results from SingleStream results. For example, a SingleStream ResNet50 result of 20 ms per sample would be counted as 2 streams, provided that the 20 ms were measured at the 99% percentile and the number of samples was at least 270,336.

Any other ideas?

**Comment by psyhtest** [comment]
This is especially worrying if the random seeds are again going to be distributed only 1 week before the deadline as per the [submission rules](https://github.com/mlperf/policies/blob/master/submission_rules.adoc#42-single-submission-round-schedule).

**Comment by christ1ne** [comment]
another idea: consider re-use of accuracy log provided if the model weights used in inference are the identical across different scenarios for all submission categories.   @aaronzhongii will that help you?

**Comment by aaronzhongii** [comment]
> another idea: consider re-use of accuracy log provided if the model weights used in inference are the identical across different scenarios for all submission categories. @aaronzhongii will that help you?

I guess i am ok. But you probably want to ask @psyhtest right?

**Comment by psyhtest** [comment]
> I guess i am ok. But you probably want to ask @psyhtest right?

:))

> another idea: consider re-use of accuracy log provided if the model weights used in inference
> are the identical across different scenarios for all submission categories.

In the above, I assumed that the weights indeed would be identical.

**Comment by TheKanter** [comment]
Group agrees that an implied offline and multi-stream score may be computed, based on a valid single stream submission. Rules must be updated to reflect this.

**Comment by christ1ne** [comment]
have we updated the rules on this @psyhtest ?

**Comment by psyhtest** [comment]
Sorry, not yet. I'll try to formalise the rule change by next week.

**Comment by christ1ne** [comment]
WG: we will review the updated PR next week.

**Comment by christ1ne** [comment]
@psyhtest any update?

**Comment by psyhtest** [comment]
@christ1ne Let me just double check what @tjablin had in mind in [his review comment](vhttps://github.com/mlperf/inference_policies/pull/168#discussion_r520741235).

**Comment by christ1ne** [comment]
@psyhtest is the PR ready?

**Comment by psyhtest** [comment]
#168 should be ready to go!
