### ISSUE TITLE
Fused about QSL

### ISSUE THREAD

**Issue by alphaRGB** [mlcommons/inference_policies#191]
I am fused about **QSL**,  I have noticed there is explaination about **QSL** in README:   For performance runs, the LoadGen will select queries uniformly at random (with replacement) from a test set. The minimum size of the performance test set for each benchmark is listed as 'QSL Size' in the table above.

Here is my question:
* QSL is short for what?  it is Query Sample Length ??
* What QSL effect?  Latency or throughoutput ?, How QSL effect performance ?
* The relationship between QSL and Dataset sample counts

**Comment by christ1ne** [comment]
you can learn more about QSL in the loadgen source code at:
https://github.com/mlcommons/inference/blob/master/loadgen/loadgen.cc#L1542

**Comment by christ1ne** [comment]
please re-open if needed
