### ISSUE TITLE
Benchmark duration is inconsistent with official website

### ISSUE THREAD

**Issue by haowang5128** [mlcommons/inference_policies#201]
Hi, 
I was checking the https://mlcommons.org/en/inference-edge-07/ page , and found the duration requirement is '60s' which is inconsistent with https://github.com/mlcommons/inference_policies/blob/master/inference_rules.adoc#3-scenarios (600s).

**Comment by tjablin** [comment]
The web page you link is for MLPerf Inference 0.7. The rules have been updated for MLPerf Inference 1.0. The minimum duration increased from one to ten minutes between 0.7 and 1.0.

**Comment by haowang5128** [comment]
> The web page you link is for MLPerf Inference 0.7. The rules have been updated for MLPerf Inference 1.0. The minimum duration increased from one to ten minutes between 0.7 and 1.0.

Oh,I see now. Thank you!
