### ISSUE TITLE
ML Perf Mobile Closed Rules Clarification - Object Detection and Image Segmentation

### ISSUE THREAD

**Issue by dylanzika-google** [mlcommons/inference_policies#223]
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-57def3f7-7fff-cb17-610f-8510a50993c2"><h2 dir="ltr" style="line-height:1.38;margin-top:18pt;margin-bottom:6pt;"><span style="font-size:16pt;font-family:'Google Sans',sans-serif;color:#ea4335;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">1 Object Detection</span></h2><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:'Google Sans',sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Can we modify the settings of TFLite_Detection_Postprocess of MobileDET?&nbsp;</span></p><h3 dir="ltr" style="line-height:1.38;margin-top:16pt;margin-bottom:6pt;"><span style="font-size:13.999999999999998pt;font-family:'Google Sans',sans-serif;color:#34a853;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Alignment with Rules</span></h3><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:'Google Sans',sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">We change TFLite_Detection_Postprocess to use fast NMS, along with some modification to detection number and thresholds. This is a kind of approximation approach, which is listed in the allowed example list in 8.2 section of rule:</span><span style="font-size:11pt;font-family:'Google Sans',sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;"><br /><br /></span></p><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:'Google Sans',sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">&ldquo;Approximations (e.g. replacing a transcendental function with a polynomial)&rdquo;</span></p><h3 dir="ltr" style="line-height:1.38;margin-top:16pt;margin-bottom:6pt;"><span style="font-size:13.999999999999998pt;font-family:'Google Sans',sans-serif;color:#34a853;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Retraining Considerations</span></h3><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:'Google Sans',sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">No retraining is required, however we do tune the fast NMS hyper parameters to improve the accuracy result.</span></p><h3 dir="ltr" style="line-height:1.38;margin-top:16pt;margin-bottom:6pt;"><span style="font-size:13.999999999999998pt;font-family:'Google Sans',sans-serif;color:#34a853;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Accuracy Validation Analysis</span></h3><br /><br /><div dir="ltr" style="margin-left:0pt;" align="left">

Task and Data Set | Target Reference Accuracy | Proposed Accuracy Achieved
-- | -- | --
Object DetectionMS-COCO 2017 | 95% of FP32 (mAp: 0.285) | After Tuning: 0.2791

</div></b>

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-a60772dd-7fff-87db-c82e-5c3abe399aa1"><h2 dir="ltr" style="line-height:1.38;margin-top:18pt;margin-bottom:6pt;"><span style="font-size:16pt;font-family:'Google Sans',sans-serif;color:#ea4335;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">2 Image Segmentation</span></h2><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:'Google Sans',sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Can we swap the order of the ResizeBilinear op and Argmax op at the end of the model?</span></p><h3 dir="ltr" style="line-height:1.38;margin-top:16pt;margin-bottom:6pt;"><span style="font-size:13.999999999999998pt;font-family:'Google Sans',sans-serif;color:#34a853;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Alignment with Rules</span></h3><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:'Google Sans',sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">The modifications make no changes to the weight values of the model and are close approximations to the original model.</span></p><h3 dir="ltr" style="line-height:1.38;margin-top:16pt;margin-bottom:6pt;"><span style="font-size:13.999999999999998pt;font-family:'Google Sans',sans-serif;color:#34a853;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Retraining Considerations</span></h3><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:'Google Sans',sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">No retraining required.</span></p><h3 dir="ltr" style="line-height:1.38;margin-top:16pt;margin-bottom:6pt;"><span style="font-size:13.999999999999998pt;font-family:'Google Sans',sans-serif;color:#34a853;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Accuracy Validation Analysis</span></h3><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:0pt;"><span style="font-size:11pt;font-family:'Google Sans',sans-serif;color:#000000;background-color:transparent;font-weight:400;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">With this change the prediction quality remains is within the acceptable range.</span></p><br /><div dir="ltr" style="margin-left:0pt;" align="left">

Task and Data Set | Target Reference Accuracy | Proposed Accuracy Achieved
-- | -- | --
SegmentationADE20K (32 classes, 512x512) | 97% of FP32 (32-class mIOU: 54.8) | After Reordering: 53.4 mIOU

</div></b>

**Comment by willc2010** [comment]
plus folks to review and comment.

**Comment by dylanzika-google** [comment]
Notes From ML Commons Mobile Working Group Discussion on June 23 2021

1 - Object Detection NMS may not be allowed in closed division (60% certain that is not allowed in closed -DK)
In ML Perf 1.0 - We wanted to avoid getting gains from Hyper Parameter Searching on NMS.
Open Division could be allowed.

2 - Did not discuss during meeting

**Comment by Mostelk** [comment]
Here are my own opinions:
1) There are many NMS variants available, and also within same NMS algorithm one can tradeoff computational complexity with accuracy. Hence if NMS algorithm or its hyperparameters are allowed to change, once can tradeoff the complexity/accuracy of their NMS algorithm with the complexity/accuracy of their network, so it will not be a consistent benchmark for closed division. If we treat the NMS parameters as weights, then changing NMS of the reference model will fall under this category which is not allowed: Modifying weights during the timed portion of an inference run (no online learning or related techniques)

2) One can view a node which fuses the resize and the Argmax as a fused node, in that case the swapping operations may be allowed under main inference rules Model Equivalence Rules (fusing or unfusing operation)
https://github.com/mlcommons/inference_policies/blob/master/inference_rules.adoc#82-model-equivalence

**Comment by freedomtan** [comment]
That's a bit tricky. Considering that those are not mathematically equivalent and there is reduction of computation (512x512 argmax over 32 classes --> 128x128 argmax over 32x32 classes, which means 1/16 computation complexity)

**Comment by rnaidu02** [comment]
@willc2010 is this resolved?

**Comment by rnaidu02** [comment]
Checked with Mobile WG and @dylanzika-google and this issue can be closed.
