### ISSUE TITLE
Definition of "component" 

### ISSUE THREAD

**Issue by DilipSequeira** [mlcommons/inference_policies#224]
Nvidia is considering entering a submission with a standard GPU that includes custom VBIOS that would not be available to customers. It is consistent with the rules of Closed division, and we think this is consistent with intent of Closed RDI.

We want to confirm with the WG that a custom VBIOS counts as a separate component under RDI rules, as the RDI rules state: "The RDI components may not be submitted as Available components until the submission cycle after next or 181 days whichever is longer".

**Comment by tjablin** [comment]
I think that's correct.

**Comment by rnaidu02** [comment]
WG agreed
