### ISSUE TITLE
Fix MLPerf Inference compatibility table

### ISSUE THREAD

**Issue by TheKanter** [mlcommons/inference_policies#238]
This table might need fixing? https://drive.google.com/file/d/1Dbz_jG4RMuB4Fugw_GWYV1gOw6P-MBpp/view

**Comment by rnaidu02** [comment]
@TheKanter  @tjablin What is the fix for Inference table? It looks good to me.

**Comment by TheKanter** [comment]
Need to figure out if run time  minimum change to 10 minutes breaks compatibility and anything else.

**Comment by TheKanter** [comment]
https://docs.google.com/spreadsheets/d/1YInL5rf-iU8CaVloVwKdU0XdrxcmhSNH2s1KlnBnCgQ/edit#gid=0 This document has pending updates and is only accessible to chairs, etc.

**Comment by rnaidu02** [comment]
Updated
