### ISSUE TITLE
Need to clean up Inference rules.adoc with recent changes for Object detector 

### ISSUE THREAD

**Issue by rnaidu02** [mlcommons/inference_policies#249]
Need to update all references to SSD-ResNet34 and SSD-MobileNet with SSD-ResNeXt50 in this rules doc https://github.com/mlcommons/inference_policies/blob/master/inference_rules.adoc

**Comment by rnaidu02** [comment]
Addressed in https://github.com/mlcommons/inference_policies/pull/250

**Comment by nv-ananjappa** [comment]
@rnaidu02 Didn't we agree that the name of the new network should be "RetinaNet"? Can we fix that?
