### ISSUE TITLE
Clarification on reading Quality Target

### ISSUE THREAD

**Issue by bitfort** [mlcommons/inference_policies#266]
Basic question but important. 

https://github.com/mlcommons/inference_policies/blob/master/inference_rules.adoc#411-constraints-for-the-closed-division
Resnet50-v1.5  "99% of FP32 (76.46%)"

How is the quality target to be read?
(A) [0.99] * [FP32 (76.46%)] = 75.695%
(B) [0.99 * FP32] = 76.46%

Based on my understanding going through previous log files, (A) appears to be the correct reading but want to confirm here.

**Comment by rnaidu02** [comment]
A is correct (75.695%)

**Comment by bitfort** [comment]
Thanks!
