### ISSUE TITLE
Is Ethernet point-to-point allowed in Network division of 3.1?

### ISSUE THREAD

**Issue by nv-ananjappa** [mlcommons/inference_policies#279]
@psyhtest asked in today's WGM: "From our discussions I recall that point-to-point Ethernet connections (without a switch in the middle) are allowed [in Network division submissions]; however, the rules are not entirely clear on this subject."

@liorkhe confirmed that point-to-point Ethernet is allowed, but wanted @DilipSequeira to confirm since they both were instrumental in the creation of the Network division rules.

@DilipSequeira has confirmed offline that @liorkhe is right: "the [permitted] fabric has to have switching capability, but that’s not the same as requiring the submission itself to have a switch." But also "it might be best to have separate sections for the fabric requirements and the system topology requirements since those are mixed together right now and cause confusion."

**Comment by nv-ananjappa** [comment]
@liorkhe Can I volunteer you to submit a PR clarifying the Network division rules better as suggested above?

**Comment by liorkhe** [comment]
@nv-ananjappa I think the text is OK when reading the rules as a whole section. I modified actually in another place to clarify. can you please check if this text change is OK. If so, I will create a pull request.
https://github.com/liorkhe/inference_policies/pull/8/files

**Comment by liorkhe** [comment]
@nv-ananjappa, @psyhtest can we conclude this one? Is it OK to submit this PR?

**Comment by liorkhe** [comment]
thanks for the review. the PR for MLcommons rules is at:
https://github.com/mlcommons/inference_policies/pull/280

**Comment by psyhtest** [comment]
Closed by merging #280.
