### ISSUE TITLE
What the minimum accuracy or mAP requirement in the open division?

### ISSUE THREAD

**Issue by xiuyangleiasp** [mlcommons/inference_policies#50]

**Comment by tjablin** [comment]
There is no minimum accuracy requirement in the Open division. The purpose of the Open division is to capture cool results that don't meet the requirements of the Closed division. For example, if a 4-bit inference system didn't meet the accuracy targets for the Closed division, the Open would still publish the results.

**Comment by tjablin** [comment]
Hi Dilip,
Some of the ideas from your [MLPerf Open division strawthing](https://docs.google.com/document/d/1SX458TLuQGeRAnZm9Ri2SPQ4ab4Mg0oWVwz9JR-b0i8/edit?ts=5d041713#heading=h.ce3l36szin) don't seem to be merged with the current rules doc.  Could you please open a PR to merge your strawthing into the rules? In particular, we should make sure that lower accuracies and tail latency tolerances are supported in open. If you don't think you can have a PR ready for Wednesday, please let me know, and I will attempt it.
Tom

**Comment by DilipSequeira** [comment]
Good idea. I'll do it.

**Comment by tjablin** [comment]
Thanks!

**Comment by tjablin** [comment]
Did this get merged?

**Comment by christ1ne** [comment]
@DilipSequeira friendly ping

**Comment by christ1ne** [comment]
@DilipSequeira I am adding this to the backlog.

**Comment by christ1ne** [comment]
WG: submitters can choose their own accuracy target in Open.
